### ISSUE TITLE
[Feature Request] custom variables

### ISSUE THREAD

**Issue by zero734kr** [wonderlandpark/dokdo#14]
I was trying to access original properties from my original eval code but I cannot access that because 'eval' itself is executed in different location.

Any idea to solve this problem? Or that feature is impossible?

* Explication:
```js
// src/commands/eval.js
// ...
const var1 = 0
const var2 = "asdf"

// node_modules/dokdo/src/commands/js.js
// access 'var1', 'var2' variables from 'src/commands/eval.js'
```

**Comment by wonderlandpark** [comment]
Maybe adding the custom variable in options of the Dokdo class would be great

**Comment by zero734kr** [comment]
Yeah, I’m waiting for this functionality
