### ISSUE TITLE
[BUG] docs error occured, if Discord.js branch v{version} is not exist.

### ISSUE THREAD

**Issue by mome0320** [wonderlandpark/dokdo#279]
in Docs Util can not be exist version(`v{number}`).

ex) if discord.js version is v13 it make source url like this.
https://raw.githubusercontent.com/discordjs/discord.js/docs/v13.json

but it 404. in result it makes error like this.

![image](https://user-images.githubusercontent.com/18746638/128629985-09958929-21f7-4f46-8ace-683f786cf128.png)

**Comment by KeepSOBP** [comment]
@wonderlandpark close required
