### ISSUE TITLE
[Feature Request] Customizable hidden text

### ISSUE THREAD

**Issue by zero734kr** [wonderlandpark/dokdo#29]
One of the features of dokdo is that it hides the token automatically.

But there are other vulnerable information that can be accessed through ``process.env`` and customizable hidden text will be useful to hide the database access key, tokens from other services etc.

**Comment by wonderlandpark** [comment]
Every Envs are not always secret. Its unnecessary.

**Comment by wonderlandpark** [comment]
Also you could do something like `...Object.values(process.env)`

**Comment by zero734kr** [comment]
Yes, but ***customizable hidden text***. The person is able to select the information to hide and if there is nothing, don't use this option

**Comment by wonderlandpark** [comment]
Already able with options.secrets

**Comment by zero734kr** [comment]
Can you write to docs about options available? Me and some people may be too lazy to see the code just to see the options available. It's crazy!
