### ISSUE TITLE
Not working at custom shard manager (kurasuta)

### ISSUE THREAD

**Issue by zero734kr** [wonderlandpark/dokdo#3]
* [src/commands/main.js:L16](https://github.com/wonderlandpark/dokdo/blob/aa2875c76741e0159d1369d4ff3f32738bc52481/src/commands/main.js#L16)

What about using:

```js
Array.isArray(client.shard.shards) ? client.shard.shards.length : client.shard.count
```

**Comment by wonderlandpark** [comment]
Looks like it's not a Bug.

This bug is only reproducing if the bot is using a custom shard manager.

So I'm converting it to enhancement

**Comment by wonderlandpark** [comment]
Supporting `kurasuta`
