### ISSUE TITLE
[BUG] Error: Invalid `client`. `client` parameter is required

### ISSUE THREAD

**Issue by pikokr** [wonderlandpark/dokdo#45]
When I use dokdo with latest version on discord.js(github), dokdo shows the error in title.
I think this bug will be fixed if this project move discord.js dependency to devDependency.

**Comment by wonderlandpark** [comment]
Could you change it to English?

**Comment by zero734kr** [comment]
If I use master branch of discord.js, the above error in title is being printed.

**Comment by zero734kr** [comment]
@wonderlandpark what about using deepEqual instead of ``instanceof`` to avoid this?

**Comment by zero734kr** [comment]
In other day I also had this problem

**Comment by pikokr** [comment]
I deleted node_modules/dokdo/node_modules/discord.js directory and now working properly.

**Comment by zero734kr** [comment]
But the problem will persist to other users. So, we need to fix this

**Comment by wonderlandpark** [comment]
> @wonderlandpark what about using deepEqual instead of ``instanceof`` to avoid this?

I'm already using instanceof but If djs version is incompatible with dokdo, this cause. Because, dokdo is using `node_modules/dokdo/node_modules/discord.js` so the fucking javascript is thinking that these are the different classes

**Comment by zero734kr** [comment]
> > @wonderlandpark what about using deepEqual instead of `instanceof` to avoid this?
> 
> I'm already using instanceof but If djs version is incompatible with dokdo, this causes. Because, dokdo is using `node_modules/dokdo/node_modules/discord.js` so the fucking javascript is thinking that these are the different classes

Yeah so what about using some deepEqual utils? Google it and this can be easily found

**Comment by zero734kr** [comment]
I also already know about instanceof “human bugs”

**Comment by wonderlandpark** [comment]
I think this would be solve by changing djs to Dev dependentcy

**Comment by zero734kr** [comment]
So, when you’ll fix this?

**Comment by zero734kr** [comment]
I’m against changing discord.js to devDependencies because tecnically it’s not “dev” dependency, for development purposes

**Comment by zero734kr** [comment]
I think checking if imported discord.js is in root node_modules or checking with deepEqual can be better than that

**Comment by wonderlandpark** [comment]
I am buzy right now so I can't fix it. If you need it, please create a PR

**Comment by KeepSOBP** [comment]
![image](https://user-images.githubusercontent.com/50764666/116233343-1f7ab300-a796-11eb-9879-cb625edc5914.png)

![image](https://user-images.githubusercontent.com/50764666/116232951-b72bd180-a795-11eb-84df-1fd22eca1a1d.png)
Still having problem
discord.js version: 12.5.3
dokdo version: 0.3.0
