### ISSUE TITLE
[Dependency] Move discord.js to peerDependencies

### ISSUE THREAD

**Issue by zero734kr** [wonderlandpark/dokdo#71]
I found on the [official nodejs blog](https://nodejs.org/es/blog/npm/peer-dependencies/) (apparently the blog has been disabled, there are no more posts in the npm category since 2013) that said that peerDependencies are list of dependencies that ignore version incompatibility. So instead of keeping discord.js as devDependency, move it to peerDependencies.

**Comment by wonderlandpark** [comment]
Please make a PR

**Comment by zero734kr** [comment]
Check this PR #73
